---
language: node_js
node_js:
  - "node"
  - "6"


cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - "npm --version"
  - "npm install -g bower"

install:
  - "npm install"

cache: yarn

script:
  - npm test


